### ISSUE TITLE
write() argument is not bytes

### ISSUE THREAD

**Issue by lidiamartinez** [tetration/Simcity3000-HD-patch#1]
Traceback (most recent call last):
  File "SCU3_HD_patch.py", line 62, in <module>
    main()
  File "SCU3_HD_patch.py", line 58, in main
    edit_hex()
  File "SCU3_HD_patch.py", line 36, in edit_hex
    logHex_data_of_executable("original_hexdata.txt")# Logs an hex data of the file before the changes
  File "SCU3_HD_patch.py", line 30, in logHex_data_of_executable
    text_file.write(hexdata)
TypeError: write() argument must be str, not bytes

**Comment by tetration** [comment]
I've finally created a version of my script that is compatible with python 3. In the python 3 version of my script I made sure to address this bug. I think its solved. Thanks for letting me know about it.

Edit: write() argument is now str, not bytes. So, chances are that you wont get this error anymore when trying to run my script under python 3
