### ISSUE TITLE
Clarify documention - Resolution must be divisible by 8 for stablity

### ISSUE THREAD

**Issue by delipunch** [tetration/Simcity3000-HD-patch#4]
Does both the vertical and horizontal resolution have to be evenly divisible by 8, or just the vertical? Do people with 1366x768 monitors need to play in 1360x768 instead, for example?

**Comment by delipunch** [comment]
Tried it myself, 1366-wide crashed when I tried to pan the view-port, but 1360-wide worked fine. I'll see if I can make a PR with a clarified readme

**Comment by tetration** [comment]
@delipunch glad you found out on your own. Sorry for not getting back to you in time. It was a busy week for me. Anyways, I've just approved your PR @delipunch thank you for contributing.
